export const RECEIVE_FILM_DETAILS = 'RECEIVE_FILM_DETAILS';
export const FETCH_FILM_DETAILS = 'FETCH_FILM_DETAILS';
export const RECEIVE_FILM_TMDB = 'RECEIVE_FILM_TMDB';
export const FETCH_FILM_TMDB = 'FETCH_FILM_DETAIL';
export const RECEIVE_IS_IN_WATCHED = 'RECEIVE_IS_IN_WATCHED';
export const FETCH_IS_IN_WATCHED = 'FETCH_IS_IN_WATCHED';
